spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vyouyou/springcloudconfigserver/
          search-paths: /config
          username: vqishiyu@163.com
          password: a1234566.
server:
  port: 7001
