spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.24.103:3307/order_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234566
  cloud:
    consul:
      host: 39.106.24.103
      port: 8500