spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.106.24.103:3306/order_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234566
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: commodity-service
#        health-check-path: /actuator/health
        instance-id: ${spring.application.name}-${random.int[10000,99999]}
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 7002